In [1]:
import pandas as pd
import nltk
from nltk.corpus import brown
from nltk import FreqDist

In [2]:
kw = pd.read_csv("./Keyword Stats 2020-05-13 at 22_32_03 - Keyword Stats 2020-05-13 at 22_32_03.csv")

In [3]:
kw.head(100)

,Keyword,Currency,Avg. monthly searches,Min search volume,Max search volume,Competition,Competition (indexed value),Top of page bid (low range),Top of page bid (high range),Ad impression share,...,Searches: Dec 2019,Searches: Jan 2020,Searches: Feb 2020,Searches: Mar 2020,Searches: Apr 2020,Concept: Otros,Concept: Mueble,Concept: Otras Marcas,Concept:,Concept: Instituci√≥n Financiera
0,ikea,EUR,N/D,1.000.000,10.000.000,Baja,2.0,"0,04","0,20",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ikea online,EUR,N/D,10,100,Media,47.0,"0,04","0,71",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ikea kallax,EUR,N/D,1,10,Baja,25.0,"0,04","0,20",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ikea family,EUR,N/D,10,100,Baja,4.0,"0,04","0,49",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ikea family,NaN,NaN
4,ikea besta,EUR,N/D,1,10,Media,40.0,"0,04","0,30",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,ikea la gavia,EUR,N/D,1,10,Baja,4.0,"0,03","0,30",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gavia,NaN,NaN
96,ikea mulig,EUR,N/D,100,1,Baja,31.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,ikea grundtal,EUR,N/D,100,1,Baja,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,ikea 2019,EUR,N/D,100,1,Alta,82.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,ikea hektar,EUR,N/D,10,100,Baja,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
kw.columns

Index(['Keyword', 'Currency', 'Avg. monthly searches', 'Min search volume',
       'Max search volume', 'Competition', 'Competition (indexed value)',
       'Top of page bid (low range)', 'Top of page bid (high range)',
       'Ad impression share', 'Organic impression share',
       'Organic average position', 'In account?', 'In plan?',
       'Searches: May 2019', 'Searches: Jun 2019', 'Searches: Jul 2019',
       'Searches: Aug 2019', 'Searches: Sep 2019', 'Searches: Oct 2019',
       'Searches: Nov 2019', 'Searches: Dec 2019', 'Searches: Jan 2020',
       'Searches: Feb 2020', 'Searches: Mar 2020', 'Searches: Apr 2020',
       'Concept: Otros', 'Concept: Mueble', 'Concept: Otras Marcas',
       'Concept:', 'Concept: Instituci√≥n Financiera'],
      dtype='object')

In [5]:
kw.drop(kw.columns.difference(['Keyword','Max search volume','Competition (indexed value)','Top of page bid (low range)','Top of page bid (high range)']), 1, inplace=True)

In [6]:
kw.head(100)

,Keyword,Max search volume,Competition (indexed value),Top of page bid (low range),Top of page bid (high range)
0,ikea,10.000.000,2.0,"0,04","0,20"
1,ikea online,100,47.0,"0,04","0,71"
2,ikea kallax,10,25.0,"0,04","0,20"
3,ikea family,100,4.0,"0,04","0,49"
4,ikea besta,10,40.0,"0,04","0,30"
...,...,...,...,...,...
95,ikea la gavia,10,4.0,"0,03","0,30"
96,ikea mulig,1,31.0,NaN,NaN
97,ikea grundtal,1,1.0,NaN,NaN
98,ikea 2019,1,82.0,NaN,NaN
99,ikea hektar,100,2.0,NaN,NaN

In [7]:
kw.shape

(1435, 5)

In [8]:
kw['Keyword'] = kw['Keyword'].apply(lambda tokenize: nltk.word_tokenize(tokenize))

In [9]:
kw.head(100)

,Keyword,Max search volume,Competition (indexed value),Top of page bid (low range),Top of page bid (high range)
0,[ikea],10.000.000,2.0,"0,04","0,20"
1,"[ikea, online]",100,47.0,"0,04","0,71"
2,"[ikea, kallax]",10,25.0,"0,04","0,20"
3,"[ikea, family]",100,4.0,"0,04","0,49"
4,"[ikea, besta]",10,40.0,"0,04","0,30"
...,...,...,...,...,...
95,"[ikea, la, gavia]",10,4.0,"0,03","0,30"
96,"[ikea, mulig]",1,31.0,NaN,NaN
97,"[ikea, grundtal]",1,1.0,NaN,NaN
98,"[ikea, 2019]",1,82.0,NaN,NaN
99,"[ikea, hektar]",100,2.0,NaN,NaN

In [11]:
#fdist = FreqDist(kw.Keyword)
#fdist

In [ ]:
kw.Keyword.value_counts()